### ISSUE TITLE
ply export does not import in blender.

### ISSUE THREAD

**Issue by Ryder17z** [guillaumechereau/goxel#221]
```
Traceback (most recent call last):
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/__init__.py", line 96, in execute
    import_ply.load(self, context, path)
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 428, in load
    return load_ply(filepath)
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 414, in load_ply
    mesh = load_ply_mesh(filepath, ply_name)
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 231, in load_ply_mesh
    obj_spec, obj, texture = read(filepath)
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 223, in read
    obj = obj_spec.load(format_specs[format], plyf)
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 113, in load
    return dict([(i.name, [i.load(format, stream) for j in range(i.count)]) for i in self.specs])
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 113, in <listcomp>
    return dict([(i.name, [i.load(format, stream) for j in range(i.count)]) for i in self.specs])
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 113, in <listcomp>
    return dict([(i.name, [i.load(format, stream) for j in range(i.count)]) for i in self.specs])
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 37, in load
    return [x.load(format, stream) for x in self.properties]
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 37, in <listcomp>
    return [x.load(format, stream) for x in self.properties]
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 102, in load
    return self.read_format(format, 1, self.numeric_type, stream)[0]
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 77, in read_format
    ans = [mapper(x) for x in stream[:count]]
  File "/home/exilefox/.local/share/Steam/steamapps/common/Blender/2.83/scripts/addons/io_mesh_ply/import_ply.py", line 77, in <listcomp>
    ans = [mapper(x) for x in stream[:count]]
ValueError: could not convert string to float: b'0,000000'

location: <unknown location>:-1
```

**Comment by guillaumechereau** [comment]
What version of goxel and blender?  Does it happen with all models?

**Comment by Ryder17z** [comment]
Only tested one so far. Goxel 0.10.4 and blender 2.83-lts

**Comment by guillaumechereau** [comment]
Could you send me the model that doesn't work?

**Comment by Ryder17z** [comment]
[vitara.gox.zip](https://github.com/guillaumechereau/goxel/files/5791681/vitara.gox.zip)

**Comment by guillaumechereau** [comment]
I just tried with current goxel build and blender 2.82a, it seemed to work.

![image](https://user-images.githubusercontent.com/107679/104156548-40580c00-5424-11eb-982f-4b9e2c7a6443.png)

Here is the exported ply file I got from goxel:
[Untitled.zip](https://github.com/guillaumechereau/goxel/files/5794465/Untitled.zip)

**Comment by Ryder17z** [comment]
Hmm. Odd.

**Comment by guillaumechereau** [comment]
Can you open the ply file I attached with your version of blender?  You can update goxel to the last version (0.10.7) maybe.

**Comment by Ryder17z** [comment]
Your file works. I have not checked if goxel has been updated yet
(installed through pacman)

**Comment by Ryder17z** [comment]
[older_untitled.ply.zip](https://github.com/guillaumechereau/goxel/files/5820883/older_untitled.ply.zip)

Here is the older export of the same model, if it's useful.
